server:
  port: 6006
  cert: "../../../bhl/.cert/combined-tma-cert.pem"
  key: "../../../bhl/.cert/tma.local+2-key.pem"

vosk:
  model_path: "../Models/vosk-model-streaming-ru"
  sample_rate: 16000
  feature_dim: 80
  chunk_ms: 100
