server:
  port: 6006
  cert: "../../../bhl/.cert/combined-tma-cert.pem"
  key: "../../../bhl/.cert/tma.local+2-key.pem"

vosk:
  model_path: "../Models/vosk-model-streaming-ru"
  sample_rate: 16000
  feature_dim: 80
  chunk_ms: 100

command_:
  enabled: true
  commands_file: "./data/commands.json"
  min_words: 2
  model:
    onnx_path: "../Models/multilingual-e5-small/onnx/model.onnx"
    tokenizer_path: "../Models/multilingual-e5-small/tokenizer.json"
    lib_path: "/home/michael/go/ort/lib/libonnxruntime.so"
    threshold: 0.92

command:
  enabled: true
  commands_file: "./data/commands.json"
  min_words: 2
  threshold: 3  # порог расстояния Левенштейна (0 = точное совпадение)

gigaam:
  enabled: true
  model_path: "/home/michael/LLM/bhl/servers/Models/gg_v3_e2e_rnnt/onnx_e2e_rnnt"
  sample_rate: 16000
  feature_dim: 64
  num_threads: 2
  provider: "cpu"

qwen:
  enabled: false  # пока заглушка
  model_path: "../Models/qwen"

logging:
  verbose: true
  profile: true  # замерять время этапов
